apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-conf
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/jmartinez-fusion/argocd-conf.git
    targetRevision: main
    path: repos
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy: {}
